### ISSUE TITLE
no longer receiving identity token

### ISSUE THREAD

**Issue by willsalz** [google/oauth2l#119]
I know this isn't the best place to post this, but I'm not sure where else to start out.

At some point in the past [ 6 months + ] I could use oauth2l with my GCP project and out would come an `id_token` field when I requested with OIDC scopes e.g.

```console
$ oauth2l fetch --scope='openid,email,profile' --type=oauth --output_format=json
```

would produce JSON with an `id_token` field.

Now when I run oauth2l version 1.2.0 for the same project, I only see the following fields: 
- access_token
- expiry
- refresh_token
- token_type

Is this a change in oauth2l? a change with GCP Auth? Maybe something with my account? Any help in tracking down the issue would be appreciated.

**Comment by willsalz** [comment]
I just pulled down the source at `v1.1.0`, built and ran the binary and the `id_token` is now showing up; looks like a possible regression?

**Comment by shinfan** [comment]
It seems like a regression introduced in https://github.com/google/oauth2l/pull/117.

I will create a PR to fix this.
