### ISSUE TITLE
 syntax error in linux pre-compiled binary

### ISSUE THREAD

**Issue by yiga2** [google/oauth2l#129]
Trying to install on ARMv7 BusyBox (router) using the pre-compiled binary.

Downloaded, decompressed and set as executable with `chmod +x oauth2l`.

Upon running the tool though, I get `./oauth2l: line 2: syntax error: unterminated quoted string`

**Comment by andyrzhao** [comment]
Hi there, that error does not look related to oauth2l itself. Are you trying to run oauth2l as part of a script? If so, I would double check to make sure the script has the correct syntax. Thanks!

**Comment by yiga2** [comment]
Found out that such error typically occur when trying to run a 64bit code in a 32bit OS. 
ARMv7 is 32bit...
Any chance you can release a Linux pre-compiled 32bit binary ? That would allow to use the tool on routers with Qualcomm ARMv7 - many.

**Comment by yiga2** [comment]
Closing as I learned compiling with go for any arch is straightforward. I did for `linux/arm` and the tool works just fine on ARMv7.
