### ISSUE TITLE
password flow

### ISSUE THREAD

**Issue by 1268** [google/oauth2l#156]
does this tool have a flow where it either spawns, or provides a Google URL where I can login, which then returns an authorization code to the tool?

**Comment by 1268** [comment]
OK yes I think that's what I am needing. do you have an example of what the client ID credentials file would look like? I have a client ID so I can create it manually

**Comment by andyrzhao** [comment]
Yes, please see https://github.com/google/oauth2l#--credentials - you can generate a client ID credential from the GCP cloud console for your project.
