### ISSUE TITLE
Cannot generate refresh token. "missing 'type' field in credentials"

### ISSUE THREAD

**Issue by hoffmanmc** [google/oauth2l#162]
I am trying to set up a connection to the Google Ads API as per [these instructions.](https://developers.google.com/google-ads/api/docs/get-started/make-first-call).

However, when I run: 
`oauth2l fetch --type oauth --credentials credentials.json --scope adwords --output_format refresh_token`
I recieve the error:
`missing 'type' field in credentials`

I've tried adding the --type flag and specifying oath to no avail. I also tried specifying "type" at the top level of the object, which returned the error: `unknown credential type: "oauth"` 

I installed using the tar file, running on Linux.

**Comment by mrohnstock** [comment]
let me guess, your OAuth client credentials.json got generated for 'web application' as I did.

You have to generate one for 'desktop application' (even you're working on a web application) as this tool here does only support credentials made for 'desktop application'.

See also #127

**Comment by andyrzhao** [comment]
Documented in: https://github.com/google/oauth2l/pull/167
