### ISSUE TITLE
missing 'type' field in credentials

### ISSUE THREAD

**Issue by robdyck** [google/oauth2l#170]
What does "missing 'type' field in credentials" mean?

Input
oauth2l fetch --type jwt --credentials app/google-services.json  --scope https://www.googleapis.com/auth/firebase.messaging

**Comment by LiveNathan** [comment]
I'm running into the same problem. Does not seem to work with the video at [Getting started with client libraries - Obtaining a refresh token](https://www.youtube.com/watch?v=_yvqUyZ72Kc).

**Comment by andyrzhao** [comment]
That error usually means your credentials file is not in the correct format (as expected by the command you are trying to execute.) For instance, a service account credentials file has a "type":"service_account" field in it ([https://github.com/google/oauth2l/blob/master/integration/fixtures/fake-service-account.json)](javascript:void(0);). I would encourage you to look over the read me section on credentials ([https://github.com/google/oauth2l?tab=readme-ov-file#--credentials)](javascript:void(0);) to ensure you are generating the credentials in the right format. Keep in mind that client-ID credentials and service account credentials are both supported by oauth2l, but serve different purposes.
