### ISSUE TITLE
Can't pull docker image

### ISSUE THREAD

**Issue by gmembre-zenika** [google/oauth2l#172]
Hello,

thanks for your work !

I tried on different computer with different public IP : I can't download the container image. It fails with the error:
```
❯ docker pull gcr.io/oauth2l/oauth2l
Using default tag: latest
Error response from daemon: Head "https://gcr.io/v2/oauth2l/oauth2l/manifests/latest": error parsing HTTP 412 response body: invalid character 'R' looking for beginning of value: "Request Rejected: Please contact project owners"
```

Same with skopeo:
```
❯ skopeo copy docker://gcr.io/oauth2l/oauth2l docker-archive:archive-file.tar
FATA[0000] initializing source docker://gcr.io/oauth2l/oauth2l:latest: Requesting bearer token: invalid status code from registry 412 (Precondition Failed)
```

My docker CLI is not authenticated on gcr.io.

What am I doing wrong ?

**Comment by mconstant** [comment]
I have this issue as well

**Comment by andyrzhao** [comment]
I just tried the above docker pull command after publishing oauth2l v1.3.1 and v1.3.2, and it seems to be working for me. Can you take another look? Thanks!

**Comment by gmembre-zenika** [comment]
2 weeks ago, I finally downloaded the previous image from a GCP project without issue.

With the release you just have done, I can pull the image also without issue from a non GCP project.
