### ISSUE TITLE
Consider printing 3LO messages to stderr

### ISSUE THREAD

**Issue by bochunz** [google/oauth2l#26]
When the oauth2l command is embedded in bash alias, such as

`alias gcurl='curl -H "$(oauth2l header --json ~/client_secret.json cloud-platform userinfo.email)" -H "Content-Type: application/json"'`

printing to stdout swallows the message, and the user won't know oauth2l is requesting a web authorization.

**Comment by wora** [comment]
There is not enough need for this feature. Close it for now.
