### ISSUE TITLE
Add G Suite domain-wide delegation support

### ISSUE THREAD

**Issue by bochunz** [google/oauth2l#34]
Documentation here: https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority

Generally oauth2l need to take another parameter as the user email and set it in the JWT while requesting access token.

**Comment by andyrzhao** [comment]
Additional resources:

https://g3doc.corp.google.com/company/teams/apps-tses/admin_console/troubleshooting/service_accounts.md?cl=head
https://developers.google.com/admin-sdk/directory/v1/guides/delegation#go

Looks like we need to set the sub field of the JWT to the email of the user we want to impersonate. Will add this feature in early Q4 2020.

**Comment by ianwinter** [comment]
Really need this feature as would make it so much easier to access what I need to!

**Comment by andyrzhao** [comment]
@ianwinter Thanks for your interest in this feature. The PR to support this is at https://github.com/google/oauth2l/pull/111, pending review. @shinfan Can you please review the PR so we can get this feature in? Thanks!

**Comment by andyrzhao** [comment]
Fixed in #111. Binaries to be updated in next OAuth2l release.
