### ISSUE TITLE
Step: Go to the following link in your browser

### ISSUE THREAD

**Issue by alankm** [google/oauth2l#37]
I notice that this step is achieved by somehow telling the OAuth2 servers not to use a redirect URI, but to instead return the verification code to the screen. Is there any way to make this step automatic? Can the library temporarily open a HTTP server and direct the callback to it so that it can authenticate without multiple manual copy-paste's by the user?

**Comment by ellipticaldoor** [comment]
Yes please

**Comment by bochunz** [comment]
Good suggestion. I've seen many other cmdlines having the similar logic, such as firebase and gcloud.

**Comment by andyrzhao** [comment]
Support added by PR #132
