### ISSUE TITLE
Cannot install oauth2l in Google Cloud Shell out of the box

### ISSUE THREAD

**Issue by michaelolson** [google/oauth2l#40]
A default Google Cloud Shell environment cannot install oauth2l.  Attempting to do so results in the following:
`$ pip install google-oauth2l
Collecting google-oauth2l
  Downloading https://files.pythonhosted.org/packages/4a/a2/270bf3e7755a394bd724dd21f65775b9f002bd2459f5767887935564ff35/google_oauth2l-1.0.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python2.7/dist-packages (from google-oauth2l) (40.0.0)
Collecting fasteners>=0.14.1 (from google-oauth2l)
  Downloading https://files.pythonhosted.org/packages/14/3a/096c7ad18e102d4f219f5dd15951f9728ca5092a3385d2e8f79a7c1e1017/fasteners-0.14.1-py2.py3-none-any.whl
Requirement already satisfied: oauth2client>=2.1.0 in /usr/local/lib/python2.7/dist-packages (from google-oauth2l) (4.1.2)
Collecting pyopenssl>=17.5.0 (from google-oauth2l)
  Downloading https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 6.1MB/s
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python2.7/dist-packages (from google-oauth2l) (0.11.3)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from google-oauth2l) (1.11.0)
Collecting monotonic>=0.1 (from fasteners>=0.14.1->google-oauth2l)
  Downloading https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=2.1.0->google-oauth2l) (3.4.2)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=2.1.0->google-oauth2l) (0.2.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=2.1.0->google-oauth2l) (0.4.3)
Collecting cryptography>=2.2.1 (from pyopenssl>=17.5.0->google-oauth2l)
  Downloading https://files.pythonhosted.org/packages/67/21/e79987f1f9abae42d666b1f89b4e78aa096acc00bbf97ad40d19b07b4a83/cryptography-2.3-cp27-cp27mu-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 6.2MB/s
Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.2.1->pyopenssl>=17.5.0->google-oauth2l) (1.1.6)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.2.1->pyopenssl>=17.5.0->google-oauth2l) (2.7)
Collecting cffi!=1.11.3,>=1.7 (from cryptography>=2.2.1->pyopenssl>=17.5.0->google-oauth2l)
  Downloading https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl (407kB)
    100% |████████████████████████████████| 409kB 17.1MB/s
Collecting asn1crypto>=0.21.0 (from cryptography>=2.2.1->pyopenssl>=17.5.0->google-oauth2l)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 20.9MB/s
Collecting ipaddress; python_version < "3" (from cryptography>=2.2.1->pyopenssl>=17.5.0->google-oauth2l)
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography>=2.2.1->pyopenssl>=17.5.0->google-oauth2l)
  Downloading https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 18.9MB/s
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/michael_olson/.cache/pip/wheels/c0/a1/27/5ba234bd77ea5a290cbf6d675259ec52293193467a12ef1f46
Successfully built pycparser
tensorflow 1.9.0 has requirement setuptools<=39.1.0, but you'll have setuptools 40.0.0 which is incompatible.
Installing collected packages: monotonic, fasteners, pycparser, cffi, asn1crypto, ipaddress, cryptography, pyopenssl, google-oauth2l
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/monotonic.pyc'
Consider using the `--user` option or check the permissions.`

The install fails because tensorflow requires a lower version of setuptools than Google Cloud Shell ships with. If tensorflow can be trimmed from the oauth2l dependencies, that's probably ideal.

It may also be worth considering having oauth2l installed by default in Google Cloud Shell.

**Comment by michaelolson** [comment]
That resolves the `montonic` issue but not the `tensorflow` issue, though the latter appears not to block `oauth2l`.

The binary gets dropped in `.local/bin/oauth2l`, which is probably less ideal than having it on the path.  Setting up `oauth2l` to be installed in Cloud Shell by default - which apparently `tensorflow` is - would likely make it available in the path.

**Comment by wora** [comment]
The current python version depends on an old python oauth library. We are considering to complete the Go version and make it more generally available.

**Comment by michaelolson** [comment]
Great, looking forward to the go version.
