### ISSUE TITLE
go get error 

### ISSUE THREAD

**Issue by LarryKetone** [google/oauth2l#65]
This is what i get when i run the go get coomand

git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> master

**Comment by andyrzhao** [comment]
@LarryKetone Did you get past this issue? You can use "-v" flag with "go get" to print out more info. For example: go get -v -u github.com/google/oauth2l

**Comment by sethvargo** [comment]
Any fetch errors should be fixed with the introduction of go modules and vendoring dependencies. If you're still experiencing problems, can you please follow the new steps in the README and open a new issue? Also note that we have precompiled binaries available not (link is in the README). Thanks!
