### ISSUE TITLE
scopePrefix breaks `openid`, `email`, `profile`

### ISSUE THREAD

**Issue by elyobo** [google/oauth2l#71]
The [automatic use](https://github.com/google/oauth2l/blob/cf46f2e826b1874ba6d03460abc2e8fe4ed4f42a/main.go#L67) of [scopePrefix](https://github.com/google/oauth2l/blob/cf46f2e826b1874ba6d03460abc2e8fe4ed4f42a/main.go#L30) breaks `openid`, `email`, `profile`

![image](https://user-images.githubusercontent.com/407806/61926185-e60a8780-afb2-11e9-8c31-70ac50dabe1b.png)

Editing the generated URL to remove the scope prefixes (i.e. using `scope=openid+email+profile` instead of the scopes shown in the screenshot) causes it to work as expected.

**Comment by andyrzhao** [comment]
Sounds like "openid", "email", and "profile" are the only exceptions we need to handle according to https://developers.google.com/identity/protocols/OpenIDConnect correct? If so, I can add a regex matcher to skip appending scopePrefix for these scopes.

**Comment by elyobo** [comment]
They're the only ones that I see without a full URL scope in the [Google Sign In scopes](https://developers.google.com/identity/protocols/googlescopes#google_sign-in).

**Comment by elyobo** [comment]
Thanks @andyrzhao and @shinfan :)
