### ISSUE TITLE
FR: output gcloud-style refresh token credentials

### ISSUE THREAD

**Issue by broady** [google/oauth2l#75]
Currently everything looks pretty oriented around access tokens. It'd be nice to be able to get refresh tokens, too, preferably in the format gcloud uses:

```
$ cat ~/.config/gcloud/application_default_credentials.json 
{
  "client_id": "32555940559.apps.googleusercontent.com",
  "client_secret": "ZmssLNjJy2998hD4CTg2ejr2",
  "refresh_token": "xxxredacted",
  "type": "authorized_user"
}
```

I looked through the code to see whether it's feasible to add this to the "fetch" command but I don't think so, it seems like it'd need to be a separate sub-command.

**Comment by andyrzhao** [comment]
Hi @broady , refresh token (and id token for openid) can be obtained by running the fetch command with the flag  "--output_format json", which will return the full token payload:
{
  "access_token": "<redacted>",
  "expires_in": 3600,
  "id_token": "<redacted>",
  "refresh_token": "<redacted>",
  "scope": "openid",
  "token_type": "Bearer"
}
Is there a specific reason to output it in the format you suggested? Would it be useful to introduce a new output_format to print out the refresh token only?

**Comment by sethvargo** [comment]
Ping @broady

**Comment by andyrzhao** [comment]
This feature has been implemented in https://github.com/google/oauth2l/pull/111, which adds a new output_format "refresh_token" that will construct the gcloud style refresh token credentials json including client_id/client_secret.
