### ISSUE TITLE
Update Instructions for Pre-compiled Binaries

### ISSUE THREAD

**Issue by andyrzhao** [google/oauth2l#83]
The instructions at https://github.com/google/oauth2l#pre-compiled-binaries does not work as written. It appears that we do not actually have any binaries for specific tags (i.e. 1.0.1). The only tag that works is "latest" (i.e. https://storage.googleapis.com/oauth2l/latest/darwin_amd64.tgz).

So we should either update the instructions to refer to "latest", or generate binaries for specific tags.

**Comment by sethvargo** [comment]
Ah sorry. I should have explained better. It will be any tag _created in the future_. If you tag 1.0.2, it will build. There was no auto-build-publish configured when Shin created 1.0.1.

I think we can update the README to say "starting with 1.0.2" and then tag a new release. What do you think @andyrzhao @shinfan?

**Comment by andyrzhao** [comment]
Is it easy to retroactively publish 1.0.1? If not, then we should update the README and tag a new release like you suggested. Also, I think it's more user-friendly to just put "latest" instead of "1.2.3" in the example download paths - I doubt most people would have a need to dig up an older version. Thanks!

**Comment by sethvargo** [comment]
I tagged 1.0.2 😄
